### ISSUE TITLE
Final Activity Diagrams

### ISSUE THREAD

**Issue by AAK-00** [trixiea-25/ISDM-A2-Tut4Grp1#18]
![Activity diagram inbound](https://user-images.githubusercontent.com/62224104/83344088-dfbd0880-a345-11ea-9603-23a819893d08.jpeg)

![Activity diagram Outbound](https://user-images.githubusercontent.com/62224104/83344119-1b57d280-a346-11ea-94e2-6e816274dba5.jpeg)

![Activity diagram TC](https://user-images.githubusercontent.com/62224104/83350742-8b377e80-a381-11ea-8eaf-a12ee1e0f612.jpeg)

**Comment by trixiea-25** [comment]
Areeba has committed to the file with the activity diagrams

**Comment by trixiea-25** [comment]
Areeba has committed the final diagrams
